version: '3.8'
services:
  prestamos-service:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: prestamos-service
    ports:
      - "8081:8081"
    env_file:
      - ../.env

    networks:
      - backend

networks:
  backend:
    driver: bridge


