version: "3.8"

services:
  prestamos-service:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: prestamos-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_R2DBC_URL: ${SPRING_R2DBC_URL}
      SPRING_R2DBC_USERNAME: ${SPRING_R2DBC_USERNAME}
      SPRING_R2DBC_PASSWORD: ${SPRING_R2DBC_PASSWORD}
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-prestamos
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8088:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
